version: '3.9'

services:
  postgres_db:
    image: postgres:alpine
    container_name: postgresdb
    restart: always
    ports:
      - '5678:5678'
    environment:
      PGPORT: 5678
      POSTGRES_USER: postgres
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgresdb
    volumes:
      - db_data:/var/lib/postgresql/data
       
volumes:
  db_data: